CXXFLAGS=-O3 -fPIC -I../core -I../VigasocoSDL/ `sdl-config --cflags`
VPATH=.:../core:../core/abadia:../core/util:../core/systems

all: ../VigasocoSDL/input/libVigasocoFakeInputPlugin.so 

OBJECTS = FakeInputKeyboardPlugin.o PluginMain.o

../VigasocoSDL/input/libVigasocoFakeInputPlugin.so: $(OBJECTS)
	$(CXX) -fPIC `sdl-config --libs` -shared $(OBJECTS) -o $@

clean:
	rm -f $(OBJECTS) ../VigasocoSDL/input/libVigasocoFakeInputPlugin.so 
