CXXFLAGS=-D__VIGASOCO_SDL_STATIC__ -D_PS3 -D_KBOOT_PS3 -Os -fPIC -I../core -I../VigasocoSDL/  -I/home/cell/SDL-1.2.13/include/
VPATH=.:../core:../core/abadia:../core/util:../core/systems:

all: ../VigasocoSDL/input/libVigasocoSDLInputPlugin.a

OBJECTS = SDLInputKeyboardPlugin.o PluginMain.o

../VigasocoSDL/input/libVigasocoSDLInputPlugin.a: $(OBJECTS)
	$(AR) cru $@ $(OBJECTS)

clean:
	rm -f $(OBJECTS) ../VigasocoSDL/input/libVigasocoSDLInputPlugin.a
