all:
	cd SDLInputKeyboardPlugin && make -f Makefile.KBOOT_PS3
	cd SDLVideoPlugins && make -f Makefile.KBOOT_PS3
	cd SDLAudioPlugin && make -f Makefile.KBOOT_PS3
	cd VigasocoSDL && make -f Makefile.KBOOT_PS3

clean:
	cd SDLInputKeyboardPlugin && make -f Makefile.KBOOT_PS3 clean
	cd SDLVideoPlugins && make -f Makefile.KBOOT_PS3 clean
	cd SDLAudioPlugin && make -f Makefile.KBOOT_PS3 clean
	cd VigasocoSDL && make -f Makefile.KBOOT_PS3 clean
	
