all:
	cd SDLInputKeyboardPlugin && make -f Makefile.PS2
	cd SDLVideoPlugins && make -f Makefile.PS2
	cd VigasocoSDL && make -f Makefile.PS2

clean:
	cd SDLInputKeyboardPlugin && make -f Makefile.PS2 clean
	cd SDLVideoPlugins && make -f Makefile.PS2 clean
	cd VigasocoSDL && make -f Makefile.PS2 clean
	
