all:
	cd SDLInputKeyboardPlugin && $(MAKE) -f Makefile.static
	cd SDLVideoPlugins && $(MAKE) -f Makefile.static
	cd SDLAudioPlugin && $(MAKE) -f Makefile.static
	cd NULLAudioPlugin && $(MAKE) -f Makefile.static
	cd VigasocoSDL && $(MAKE) -f Makefile.static

clean:
	cd SDLInputKeyboardPlugin && $(MAKE) -f Makefile.static clean
	cd SDLVideoPlugins && $(MAKE) -f Makefile.static clean
	cd SDLAudioPlugin && $(MAKE) -f Makefile.static clean
	cd NULLAudioPlugin && $(MAKE) -f Makefile.static clean
	cd VigasocoSDL && $(MAKE) -f Makefile.static clean
	
