CXXFLAGS=-D__VIGASOCO_SDL_STATIC__ -O3 -I../core -I../VigasocoSDL/ `sdl2-config --cflags`
#CXXFLAGS=-g -D__VIGASOCO_SDL_STATIC__ -O3 -I../core -I../VigasocoSDL/ `sdl2-config --cflags`
#CXXFLAGS=-Os -D__VIGASOCO_SDL_STATIC__ -I../core -I../VigasocoSDL/ `sdl2-config --cflags`
VPATH=.:../core:../core/abadia:../core/util:../core/systems

OBJECTS = SDLAudioPlugin.o NULLAudioPlugin.o PluginMain.o

../VigasocoSDL/audio/libVigasocoSDLAudioPlugin.a: $(OBJECTS)
	mkdir -p $(dir $@)
	$(AR) cru $@ $(OBJECTS)

# para comprobar que no le faltan dependencias por resolver a la libreria
test: test.o
	$(CXX) -g test.o -o test -l../VigasocoSDL/audio/libVigasocoSDLAudioPlugin.a `sdl2-config --libs`

clean:
	rm -f $(OBJECTS) ../VigasocoSDL/audio/libVigasocoSDLAudioPlugin.a test test.o
