#CXXFLAGS=-g -D__VIGASOCO_SDL_STATIC__ -O3 -I../core -I../VigasocoSDL/ `sdl2-config --cflags`
CXXFLAGS=-D__VIGASOCO_SDL_STATIC__ -O3 -I../core -I../VigasocoSDL/ `sdl2-config --cflags`
VPATH=.:../core:../core/abadia:../core/util:../core/systems

OBJECTS = SDLDrawPlugin.o SDLVideoPlugins.o SDLDrawPlugin8bpp.o SDLDrawPlugin24bpp.o SDLDrawPluginPaletaGrises8bpp.o PluginMain.o

../VigasocoSDL/video/libVigasocoSDLDrawPlugin.a: $(OBJECTS)
	mkdir -p $(dir $@)
	$(AR) cru $@ $(OBJECTS)

# para comprobar que no le faltan dependencias por resolver a la libreria
test: test.o
	$(CXX) -g test.o -o test -l../VigasocoSDL/video/libVigasocoSDLDrawPlugin.a `sdl2-config --libs`

clean:
	rm -f $(OBJECTS) ../VigasocoSDL/video/libVigasocoSDLDrawPlugin.a test test.o
